baseURL = "https://ssatosays.github.io/blog"
title = "ssatosays/blog"
languageCode = "en-us"
paginate = "20"
theme = "mainroad"
googleAnalytics = "G-1Z8YRRRKXW"

[menu]
[[menu.main]]
  name = "HOME"
  pageRef = "/"
  weight = "10"
[[menu.main]]
  name = "ABOUT"
  pageRef = "/about"
  weight = "20"

[Author]
  name = "Sota Sato"
  bio = "Software Developer"
  avatar = "https://avatars.githubusercontent.com/u/86867075"

[Params]
  subtitle = "Develop | Other themes"
  description = "Develop | Other themes"
  copyright = "ssatosays/blog"
  opengraph = true
  twitter_cards = true
  readmore = false
  authorbox = true
  pager = true
  post_meta = ["date", "categories"]
  mainSections = ["posts"]
  highlightColor = "#005851"
  customCSS = ["css/custom.css"]
  customJS = ["js/custom.js"]

[Params.sidebar]
  home = "right"
  list = "right"
  single = false
  widgets = ["recent", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = "5"
  categories_counter = true
  tags_counter = true

[Params.widgets.social]
  email = "ssatosays@gmail.com"
