baseURL = "/"
title = "ssatosays/blog"
languageCode = "en-us"
paginate = "20"
theme = "mainroad"

[Author]
  name = "Sota Sato"
  bio = "Software Developer"
  avatar = "https://avatars.githubusercontent.com/u/86867075"

[Params]
  description = "Develop | Other themes"
  opengraph = true
  twitter_cards = true
  readmore = false
  authorbox = true
  pager = true
  post_meta = ["date", "categories"]

[Params.logo]
  subtitle = "Develop | Other themes"
